sudo: false
env:
  - CXX=g++-4.8
language: node_js

node_js:
  - 0.8
  - 0.10
  - 0 #Latest 0.x.x build.
  - 3 #Latest io.js build.
  - 4.2.4 #LTS
  - stable
  
matrix:
  allow_failures:
    - node_js: 0.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - zlib1g-dev
      - libpng12-dev
      - libxtst-dev
      - g++-4.8
      - gcc-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start